--Vistas

CREATE OR REPLACE VIEW V_ORGANIZACIONES AS(
    SELECT PROYECTOS.IDORGANIZACION, ORGANIZACIONES.NOMBRE, PROYECTOS.IDPROYECTO, PROYECTOS.DESCRIPCION FROM ORGANIZACIONES JOIN PROYECTOS ON PROYECTOS.IDORGANIZACION=ORGANIZACIONES.IDORGANIZACION
)

CREATE OR REPLACE VIEW ConsultaOficina AS (SELECT * FROM OFICINAS);

CREATE OR REPLACE VIEW V_consultaBienes AS (
    SELECT IDBIEN, SERVICIOS.NOMBRE AS SERVICIO, PRODUCTOS.NOMBRE AS PRODUCTO FROM BIENESOFRECIDOS
    JOIN SERVICIOS ON BIENESOFRECIDOS.IDSERVICIO=SERVICIOS.IDSERVICIO
    JOIN PRODUCTOS ON BIENESOFRECIDOS.IDPRODUCTO=PRODUCTOS.IDPRODUCTO
);

CREATE OR REPLACE VIEW V_CONSULTACARPETA AS(
    SELECT IDCARPETA, DESCRIPCION, ESTADO FROM CARPETAS
);

--Indices
CREATE INDEX NombreOficina_carpeta
    ON CARPETAS (nombreOficina);

CREATE INDEX NombreOficina_compra
    ON COMPRAS (nombreOficina);

CREATE INDEX NombreOficina_empleado
    ON EMPLEADOS (nombreOficina);

--IndicesVistasOk
SELECT * FROM V_CONSULTACARPETA WHERE IDCARPETA=37;

SELECT * FROM ConsultaOficina WHERE NOMBRE='Oficina de gobierno';

SELECT * FROM V_ORGANIZACIONES WHERE IDORGANIZACION=14;

SELECT * FROM V_CONSULTACARPETA WHERE IDCARPETA=30;


SELECT * FROM CARPETAS WHERE NOMBREOFICINA='Oficina de gobierno';

SELECT * FROM COMPRAS WHERE NOMBREOFICINA='Oficina de gobierno';

SELECT * FROM EMPLEADOS WHERE NOMBREOFICINA='Oficina de gobierno';

--Xvistas
DROP VIEW V_ORGANIZACIONES;
DROP VIEW ConsultaOficina;
DROP VIEW V_consultaBienes;
DROP VIEW V_CONSULTACARPETA;

--Xindices

DROP INDEX NombreOficina_carpeta;
DROP INDEX NombreOficina_compra;
DROP INDEX NombreOficina_empleado;
